import '.././globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'chat',
  description: 'Generated by create next app',
}

export default function ChatLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={inter.className}>
        <section>Mantappu</section>
        {children}
        </body>
    </html>
  )
}